Annual Additional Capacity Retired due to Early Retirement Policy[hard coal es] = 2000
Fraction of Additional Demand Response Potential Achieved = 0.112
Fraction of F Gas Destruction Achieved = 1
Fraction of F Gas Inspct Maint Retrofit Achieved = 1
Fraction of F Gas Recovery Achieved = 1
Fraction of F Gas Substitution Achieved = 1
Policy Implementation Schedule Selector = 4
Renewable Portfolio Std Percentage = 0.52
